// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import NitroAPI from 'nitro-api';

const client = new NitroAPI({
  username: 'My Username',
  password: 'My Password',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource reservation', () => {
  // Prism tests are disabled
  test.skip('applyPayment', async () => {
    const responsePromise = client.reservation.applyPayment();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('applyPayment: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.applyPayment(
        {
          id: 66110,
          cruiseReservation: {
            id: 114090,
            syncInfo: {
              apiSyncInfo: {
                token: 'X7sgay0T20iRYDSnVxpdSYJiRWwAVpMA',
                lastSyncOn: '20-Feb-2023 05:29:59',
                sessionId: 'a7346091-1a57-495d-8262-456c00569300',
              },
              supplierSyncInfo: {
                token: '417983',
                lastModifiedOn: '20-Feb-2023 05:44:54',
                lastSyncOn: '20-Feb-2023 05:29:55',
              },
            },
          },
          paymentToProcess: { amount: 1053.46, cardToken: 'f5d94630-61d8-4bf5-811d-1ca43a2882dd' },
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });

  // Prism tests are disabled
  test.skip('cancelReservation', async () => {
    const responsePromise = client.reservation.cancelReservation();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('cancelReservation: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.cancelReservation(
        {
          body: '//This request contains only mandatory elements\r\n{\r\n    "id": 65826, // id received \r\n    "cruiseReservation": {\r\n        "id": 113806\r\n    },\r\n    "trackingInfo": {\r\n        "token": "EQTEMPKEN"\r\n    }\r\n}',
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });

  // Prism tests are disabled
  test.skip('confirmReservation', async () => {
    const responsePromise = client.reservation.confirmReservation();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('confirmReservation: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.confirmReservation(
        {
          body: '//This message is only supported by MSC Cruiseline\r\n{\r\n    "id": 65858,\r\n    "cruiseReservation": {\r\n        "id": 113838,\r\n        "syncInfo": {\r\n            "supplierSyncInfo": {\r\n                "token": "", //This is Token Generated by Read Booking From Supplier API\r\n                "lastSyncOn": "02-Feb-2023 04:11:56"\r\n            },\r\n            "apiSyncInfo": {\r\n                "token": "a1kkiv0E20g3vF18lJQYR5IBaWX0rvzB",\r\n                "sessionId": "7c5dbc37-9494-4718-9201-6965f4aefcc1",\r\n                "lastSyncOn": "02-Feb-2023 04:11:59"\r\n            }\r\n        }\r\n    }\r\n}',
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });

  // Prism tests are disabled
  test.skip('readFromSupplier', async () => {
    const responsePromise = client.reservation.readFromSupplier();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('readFromSupplier: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.readFromSupplier(
        {
          body: '{\r\n    "id": 88715,\r\n    "cruiseReservation": {\r\n        "id": 136582,\r\n        "readPreferences": {\r\n            "mode": "View", //Possible values are View/Modify/Pay\r\n            "autoSyncOption": "NOLOCK" //Possible values are NOLOCK,LOCK,LOCKPRICES\r\n        }\r\n    },\r\n    "trackingInfo": {\r\n        "token": "EQTEMPKEN"\r\n    }\r\n}',
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });

  // Prism tests are disabled
  test.skip('readReservation', async () => {
    const responsePromise = client.reservation.readReservation();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('readReservation: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.readReservation(
        {
          id: 65822,
          cruiseReservation: { id: 113802 },
          trackingInfo: { token: 'EQTEMPKEN' },
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });

  // Prism tests are disabled
  test.skip('releaseReservation', async () => {
    const responsePromise = client.reservation.releaseReservation();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('releaseReservation: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.reservation.releaseReservation(
        {
          body: '//This message is only supported by Royal Caribbean Cruiseline (RCCL)\r\n{\r\n    "id": 65860,\r\n    "cruiseReservation": {\r\n        "id": 113840,\r\n        "syncInfo": {\r\n            "supplierSyncInfo": {\r\n                "token": "2746e2",\r\n                "lastSyncOn": "02-Feb-2023 05:04:54",\r\n                "lastModifiedOn": "02-Feb-2023 05:19:52"\r\n            },\r\n            "apiSyncInfo": {\r\n                "token": "2D0V8QQF20hNWWHSYO4BRaUxA5KPX+HK",\r\n                "sessionId": "d261594d-ee60-4501-a531-03928f5fe1ca",\r\n                "lastSyncOn": "02-Feb-2023 05:04:58"\r\n            }\r\n        }\r\n    }\r\n}',
          SiteItemId: '{{Nitro.Sandbox.SiteItemId}}',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(NitroAPI.NotFoundError);
  });
});
